#!/bin/bash --login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -N anosim
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

compare_categories.py --method anosim -i ./cdout2/bdiv_even30000/weighted_unifrac_dm.txt -m ~/Updatedmf.tsv -c Time -o anosim_time -n 99


echo "closing environment"
conda deactivate
