#!/bin/bash --login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -N comp_alpha_div
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

compare_alpha_diversity.py -i ./cdout2/arare_max30000/alpha_div_collated/PD_whole_tree.txt -m Updatedmf.tsv  -c Time -d 100 -o Time_PD100

echo "closing environment"

conda deactivate

#end script
