#!/bin/bash --login
#PBS -l walltime=00:10:00
#PBS -l select=1:ncpus=1
#PBS -N summarise_taxa
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
conda deactivate
conda activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/bioc0023/
cd ~/output/bioc0023/

# QIIME Code

summarize_taxa.py -i ./otus2/otu_table.biom -o ./tax2


echo "closing environment"
conda deactivate
